services:
  frontend:
    build: ./frontend
    container_name: frontendcontainer01
    ports:
      - 5174:5174
    environment:
      - CLOUDINARY_API="VALUE"
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend
          target: /src 
          action: sync
  backend:
    build: ./backend
    container_name: backendcontainer01
    ports:
      - 5174:3000
    environment:
      - MONGO_ATLAS_URL=""
      - CLIENT_SECRET=""
      - API_KEY=""
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend
          action: sync